### PR TITLE
Update operators.csv

### PR DESCRIPTION
**Pull request by ursinn**

### CODE REVIEW

**Comment by lspgn** [comment]
They seem to have signed prefixes but I think they are relying on their upstream to do the filtering (which can be ok). But seeing differences between Zurich and London.
Could you confirm with traceroutes to invalid.rpki.cloudflare.com?

**Comment by ursinn** [comment]
Zurich
Zurich
London
London

**Comment by lspgn** [comment]
Looks like there was an issue on NTT side.
They should be safe since default behind a RPKI-safe network.

**Comment by lspgn** [comment]
Closing this one as it's fixed in #444

**Pull request closed without merging**
