### PR TITLE
Adding 3 confirmed unsafe German ISP's to the list

### PR DESCRIPTION
**Pull request by pyramidenkoenig**

### CODE REVIEW

**Comment by cron2** [comment]
Hi,

AS5539 here... I was pointed to this, and just checked via your web site.  It tells me

"Your ISP (SpaceNet AG, AS5539) implements BGP safely. It correctly drops invalid prefixes. Tweet this →
Details
fetch https://valid.rpki.cloudflare.com
  correctly accepted valid prefixes

fetch https://invalid.rpki.cloudflare.com
  correctly rejected invalid prefixes"

so I would very much prefer to be listed as *safe*, not as unsafe...

**Comment by cron2** [comment]
Arguably this could be because I only turned on RPKI filtering towards DECIX just yesterday... so if you tested 2 days ago (your commit date), you'd see a different result.  ROA signing has been in place since many years.

**Comment by pyramidenkoenig** [comment]
@cron2 i changed the rating of SpaceNet after revisiting and testing it again. Thanks for pointing out that change.

**Comment by lspgn** [comment]
@cron2 Thank you for the deployment! Happy to put a statement in the updates if you wish!

**Pull request merged**
