### PR TITLE
Update Australian Providers

### PR DESCRIPTION
**Pull request by Mioptevo**

### CODE REVIEW

**Comment by lspgn** [comment]
@Mioptevo thank you for your contribution.
Superloop (AS38195) did not sign their prefixes. They seem to be protected through Telia and Hurricane Electric. This would also require to test the reachability via IXPs. I wouldn't put fully safe.

For Core-Backbone (AS33891): looks good, they do not announce prefixes (even though lots of IPs are signed by them). Also found the statement from 2019: https://www.core-backbone.com/en/ab-sofort-ist-rpki-in-unserem-netz-aktiv/#

**Comment by Mioptevo** [comment]
@lspgn Thanks, I've updated Superloop to be unsafe. Looks like the announcement is only selectively dropping invalids: https://twitter.com/rickjcarter/status/1273764163773362176

**Comment by lspgn** [comment]
Thanks for the clarification!
Will merge.

**Comment by lspgn** [comment]
Also noticed this tweet. https://twitter.com/timoidpls/status/1277839233760149507
We can put partially safe in that case.

**Pull request merged**
