### PR TITLE
Update operators.csv

### PR DESCRIPTION
**Pull request by tedtrp**
Added PenTeleData.

### CODE REVIEW

**Comment by lspgn** [comment]
Hi @tedtrp,
could you sort it by as-rank and remove `AS` prefix from the asn?

Thank you

**Comment by tedtrp** [comment]
Yes, if I knew how to. As you can tell I am new. Any tips/info?

Please and thank you

**Comment by tedtrp** [comment]
Yes, if I knew how to. As you can tell I am new. Any tips/info?

Please and thank you


    On Sunday, September 6, 2020, 12:39:27 PM EDT, Louis <notifications@github.com> wrote:  
 
 


Hi @tedtrp,
could you sort it by as-rank and remove AS prefix from the asn?

Thank you

**Comment by lspgn** [comment]
I'm not sure Github allows re-editing a PR from their interface.
Without using [git/command line](https://guides.github.com/activities/hello-world/#commit), you will have to start again (instructions in [CONTRIBUTING.md](https://github.com/cloudflare/isbgpsafeyet.com/blob/master/CONTRIBUTING.md)):
The line has to be inserted above line 156 (IBM) which has as-rank 1062.

Thank you

**Comment by tedtrp** [comment]
Ok.
Did you guys/gals accept the twitter update file too? Where I added PenTeleData
Please and thank you
    On Sunday, September 6, 2020, 10:00:32 PM EDT, Louis <notifications@github.com> wrote:  
 
 


I'm not sure Github allows re-editing a PR from their interface.
Without using git/command line, you will have to start again (instructions in CONTRIBUTING.md):
The line has to be inserted above line 156 (IBM) which has as-rank 1062.

Thank you

**Comment by lspgn** [comment]
@tedtrp thank you :) accepted and merge both PRs. Will close this one.

**Pull request closed without merging**
