### PR TITLE
Update operators.csv

### PR DESCRIPTION
**Pull request by robertwglee**
Rogers,ISP,signed,partially safe,812,198

### CODE REVIEW

**Comment by lspgn** [comment]
@robertwglee do you have more information about the origin validation deployment?
I see around 30% prefixes signed.
I see 99.208.0.0/12 173.32.0.0/14 have the ROAs.
[Additionally, especially for eyeball networks](https://github.com/cloudflare/isbgpsafeyet.com/blob/master/CONTRIBUTING.md), we prefer indicating partially safe when some filtering is put in place.

**Comment by suporterede1** [comment]
Please put the country code in this list.

**Comment by digizeph** [comment]
From our observations, AS812 no-longer filters RPKI invalid since July 2022.

**Comment by digizeph** [comment]
Closing this PR now based on recent test results. @robertwglee thank you for submitting this PR, and please feel free to reopen it if things regarding AS812 change.

**Pull request closed without merging**
