### PR TITLE
operators: Add TDC and Hi3G as unsafe

### PR DESCRIPTION
**Pull request by kennylevinsen**
TDC operates brands such as YouSee, Hi3G operates 3 Denmark and 3
Sweden.

### CODE REVIEW

**Comment by jejenone** [comment]
Thanks for your pull-request! We are looking at ways to add new networks to the list in an organized way. Stay tuned until we bring these changes next week.

**Comment by heni123321** [comment]
TDC has put ROAs on all of there BGP announcements.

**Comment by kennylevinsen** [comment]
TDC A/S (AS3292, through YouSee) and Hi3G Access AB (AS44034, through 3) are still failing the test as of right now.

**Comment by heni123321** [comment]
Yes but TDCs IPs has been signed ref https://bgp.he.net/AS3292#_prefixes

**Comment by lspgn** [comment]
Added both as unsafe.

**Pull request closed without merging**
