### PR TITLE
Fix UTF-8 characters causing issues on Twitter

### PR DESCRIPTION
**Pull request by lspgn**
Replacing by dash

Screen Shot 2020-06-05 at 1 12 56 PM

### CODE REVIEW

**Comment by adamschwartz** [comment]
The issue here was not the character in the `<title>`.

The issue is that we’re serving `content-type: "text/html"`, when we should be serving `content-type: "text/html; charset=utf-8"`.

image

**Comment by adamschwartz** [comment]
@EverlastingBugstopper I found https://github.com/cloudflare/kv-asset-handler/blob/9df933b647680092f230fd26c9ed76f7ec5035de/src/index.ts#L112-L114 which I believe are responsible for making this happen. Would you be able to help me figure out why that doesn’t seem to be added in this case?

**Comment by adamschwartz** [comment]
It looks like this was only just added to `kv-asset-handler` via https://github.com/cloudflare/kv-asset-handler/pull/97. Once a new release is cut we should be able to update that package.

**Comment by adamschwartz** [comment]
This is now fixed! Thanks so much @EverlastingBugstopper 

image

**Comment by EverlastingBugstopper** [comment]
Glad I could help!

**Comment by adamschwartz** [comment]
image

Verifying the fix is actually live on Twitter.

**Pull request merged**
