### PR TITLE
Add Vivacom/BTC (ISP)

### PR DESCRIPTION
**Pull request by DoNotSpamPls**

### CODE REVIEW

**Comment by FozzieHi** [comment]
Can you post a screenshot of the https://isbgpsafeyet.com test as well as the https://sg-pub.ripe.net/jasper/rpki-web-test/ test.

**Comment by DoNotSpamPls** [comment]
Huh, weird - when running Cloudflare's test, everything is 👍.
However, when running the RIPE one, it fails:

RIPE test
CloudFlare test

**Comment by FozzieHi** [comment]
@lspgn Might be filtering peers or blocking the test somehow?

**Comment by lspgn** [comment]
I ran a few RIPE Atlas probes:
One probe succeeded reaching the prefix.
They might be load-balancing traffic or have multiple exit points. Some may not have RPKI enabled. I don't think we should add them as "safe".

Screen Shot 2020-05-06 at 1 20 40 PM

Screen Shot 2020-05-06 at 1 22 24 PM

**Comment by FozzieHi** [comment]
They do sign 97% of their routes so we can change it to signed,unsafe unless this filtering issue is now resolved?

**Comment by DoNotSpamPls** [comment]
I changed the status to "partially safe", let me know if any other changes need to be done.

**Pull request merged**
