### PR TITLE
Add GTT

### PR DESCRIPTION
**Pull request by job**
Add GTT

### CODE REVIEW

**Comment by jejenone** [comment]
Is this official now ? Last I heard they were finishing deploying on customer sessions.

**Comment by job** [comment]
I confirmed with my measurements. What else do we need?

**Comment by jejenone** [comment]
Screenshot 2020-05-05 12 07 32

We're still seeing our invalid on BGPlay

**Comment by jejenone** [comment]
ignore me. It is indeed rejected

**Comment by job** [comment]
Even if that one prefixes were accepted, I think we need to look further beyond and be careful not to judge a large scale deployment by a single observation. The RPKI Invalid BGP route path count with _3257_ anywhere in the AS_PATH decreased from from thousands to triple digits.

**Pull request merged**
