### PR TITLE
Add Vodafone-Ziggo

### PR DESCRIPTION
**Pull request by ties**
**Are likely filtering the "RPKI smiley" by RIPE**

They are signing. Since it is an end-user network I would mark them as unsafe.
Screenshot 2020-05-05 at 11 36 31
Screenshot 2020-05-05 at 11 36 25
Screenshot 2020-05-05 at 11 36 11

### CODE REVIEW

**Comment by FozzieHi** [comment]
We have cases for signed as both unsafe & partially safe, @lspgn can you clarify?

**Comment by ties** [comment]
> We have cases for signed as both unsafe & partially safe, @lspgn can you clarify?

I noticed that and I personally feel like end-user networks networks that are signed should err to the side of unsafe. I'll switch my PRs over to `partially safe` if that is more applicable.

By the way the RPKI smiley result seem to be spurious. I just tested [pings to NTT/Job Snijders/RIPE](https://atlas.ripe.net/measurements/25085994/#!probes)'s test using Atlas and the Vodafone-Ziggo probes in the result do not appear to be filtering that IP now.

**Comment by FozzieHi** [comment]
I think we should be consistent, Amazon only signs but has a partially safe tag, I think Amazon deals with a lot more traffic than these ISPs.

Vodafone-Ziggo are probably only filtering peers which is another partially safe result.

**Comment by FozzieHi** [comment]
I think we should change this one to "Ziggo,ISP,signed + filtering peers only,partially safe,33915,1014" as they are still filtering peers, not sure about just signing but I think we should be consistent with everyone if they're just signing.

**Comment by ties** [comment]
> I think we should be consistent, Amazon only signs but has a partially safe tag, I think Amazon deals with a lot more traffic than these ISPs.

I think this should be consistent. However we may need to consider that the threat model differs.:
As a cloud-provider, you want to protect routes for your ip ranges that your customers use from being spoofed. You want to be reachable from as many clients as possible. That is why you sign but why you may skip filtering.
As an ISP you want to prevent your customer's from being redirected to an attacker's website. That is why you should filter.

> Vodafone-Ziggo are probably only filtering peers which is another partially safe result.

I do not think they are filtering. I re-tested (since the test target was reachable from atlas probes) and the RPKI smiley appears to have been a fluke:
Screenshot 2020-05-05 at 15 30 12

**Comment by FozzieHi** [comment]
I do agree, perhaps we should create a separate issue for this.

**Comment by lspgn** [comment]
@FozzieHi : 
> We have cases for signed as both unsafe & partially safe, @lspgn can you clarify?
We probably didn't account for all the different cases originally.
Since they are eyeball, I'd prefer setting them unsafe, unless they confirm they are doing RPKI filtering.

**Pull request merged**
