### PR TITLE
Updates Aura Denmark to be safe

### PR DESCRIPTION
**Pull request by kjeldahl**

### CODE REVIEW

**Comment by lspgn** [comment]
Hello,
Could you provide more information?
I do not see any signed prefixes or any information about origin validation.

**Comment by kjeldahl** [comment]
I am sorry but I only have the information from the https://isbgpsafeyet.com page which told me that BGP was safe. Which it was not when I originally submitted that Aura was unsafe.
How and where can I get the information you request?

**Comment by lspgn** [comment]
@kjeldahl 
Unfortunately, for this particular situation, it is not straightforward for me to see that it actually is safe.

Could you run a traceroute command to invalid.rpki.cloudflare.com and rpki-invalid-beacon.meerval.net? (eg: `traceroute -w1 invalid.rpki.cloudflare.com`)
And could you tell me what you see behind http://www.ripe.net/s/rpki-test

I did not see any prefixes signed on our [dashboard](https://rpki.cloudflare.com/?view=bgp&prefix=&asn=204274) so that made be doubt (it's a criterion for being "safe").
If they are filtering, the procedure above would help me figure out where it happens (and if it's based on RPKI).
It could also be one of their provider that is doing the filtering.

Thank you

**Comment by kjeldahl** [comment]
I have attached the output from the traceroutes and the rpiki-test site:

The rpiki-test yields:

A big smiley and
```
testing valid ROA...[passed]

testing invalid ROA (5sec)...[passed]

Your ASN is AS204274, your prefix is 85.184.128.0/19 and your network is dropping RPKI invalid BGP routes.
```

```
$ traceroute -w1 invalid.rpki.cloudflare.com
traceroute: Warning: invalid.rpki.cloudflare.com has multiple addresses; using 103.21.244.14
traceroute to invalid.rpki.cloudflare.com (103.21.244.14), 64 hops max, 52 byte packets
 1  router (192.168.1.1)  2.564 ms  1.516 ms  1.248 ms
 2  85.184.146.1 (85.184.146.1)  2.158 ms  3.936 ms  3.777 ms
 3  arhcords01-ae45-0.aura-net.dk (185.107.201.2)  4.708 ms  6.432 ms  7.936 ms
 4  * * *
 5  * * *
...
64 * * *
```

```
$ traceroute -w1 rpki-invalid-beacon.meerval.net
traceroute to rpki-invalid-beacon.meerval.net (209.24.0.3), 64 hops max, 52 byte packets
 1  router (192.168.1.1)  3.796 ms  1.442 ms  1.266 ms
 2  85.184.146.1 (85.184.146.1)  4.010 ms  4.214 ms  3.798 ms
 3  skacords01-ae45-0.aura-net.dk (185.107.201.0)  4.783 ms  4.434 ms
    arhcords01-ae45-0.aura-net.dk (185.107.201.2)  5.113 ms
 4  * * *
....
64 * * *
```

**Pull request merged**
