### PR TITLE
Add Salt.ch/AS15796

### PR DESCRIPTION
**Pull request by CookieCr2nk**
Adding Support Twitter Account (https://twitter.com/SaltMobile_Care) AS15796 to twitter.csv

### CODE REVIEW

**Comment by FozzieHi** [comment]
Can you order it correctly?

**Comment by CookieCr2nk** [comment]
What du you mean, i dont understand your question?

**Comment by FozzieHi** [comment]
It should be ordered by AS, 15796 is smaller than 135478. If you go up in the file you'll see the ASNs with 5 digits.

**Comment by CookieCr2nk** [comment]
I have updated the twitter.csv now with the right order.

**Comment by FozzieHi** [comment]
Can you remove the old one as well?

**Comment by CookieCr2nk** [comment]
Done :)

**Comment by FozzieHi** [comment]
Thanks! @lspgn looks ready for merge

**Comment by lspgn** [comment]
Thank you :)

**Pull request merged**
