### PR TITLE
RPKI configure in Edgeuno network

### PR DESCRIPTION
**Pull request by jeanrmiranda**
RPKI  configure in Edgeuno network.

image

The edgeuno is with rpki configured and with drop for all invalid ROA.

dropping on all invalid routes in all countries and for routing peering transit and customers

### CODE REVIEW

**Comment by lspgn** [comment]
Hi @jeanrmiranda 
I can still reach your network from an invalid prefix.
Could you share details on your origin validation?

Thank you

**Comment by jeanrmiranda** [comment]
> I can still reach your network from an invalid prefix.
> Could you share details on your origin validation?

@lspgn yes, and what router you see ?
set policy-options policy-statement rpki-validation term blackhole-v6 from family inet6
set policy-options policy-statement rpki-validation term blackhole-v6 from community BLACKHOLE
set policy-options policy-statement rpki-validation term blackhole-v6 from route-filter ::0/0 prefix-length-range /128-/128
set policy-options policy-statement rpki-validation term blackhole-v6 then validation-state invalid
set policy-options policy-statement rpki-validation term blackhole-v6 then community add RPKI-INVALID
set policy-options policy-statement rpki-validation term blackhole-v6 then next policy
set policy-options policy-statement rpki-validation term blackhole from community BLACKHOLE
set policy-options policy-statement rpki-validation term blackhole from route-filter 0.0.0.0/0 prefix-length-range /32-/32
set policy-options policy-statement rpki-validation term blackhole then validation-state invalid
set policy-options policy-statement rpki-validation term blackhole then community add RPKI-INVALID
set policy-options policy-statement rpki-validation term blackhole then next policy
set policy-options policy-statement rpki-validation term validated-routes from validation-database valid
set policy-options policy-statement rpki-validation term validated-routes then validation-state valid
set policy-options policy-statement rpki-validation term validated-routes then community add RPKI-VALID
set policy-options policy-statement rpki-validation term validated-routes then next policy
set policy-options policy-statement rpki-validation term invalid-routes from validation-database invalid
set policy-options policy-statement rpki-validation term invalid-routes then validation-state invalid
set policy-options policy-statement rpki-validation term invalid-routes then community add RPKI-INVALID
set policy-options policy-statement rpki-validation term invalid-routes then reject
set policy-options policy-statement rpki-validation term unknown-routes from protocol bgp
set policy-options policy-statement rpki-validation term unknown-routes then validation-state unknown
set policy-options policy-statement rpki-validation term unknown-routes then community add RPKI-UNKNOWN
set policy-options policy-statement rpki-validation term unknown-routes then next policy

**Comment by lspgn** [comment]
Screen Shot 2020-06-25 at 10 05 42 AM

I digged a bit more into your looking glass and found the reason it could still reach an invalid prefix. The routes are correctly rejected but it is still using the default gateway (which is fine and still safer from hijacks).
Would you be able to change your default route to a transit dropping invalid prefixes? (GTT, Cogent, NTT, Telia)

**Comment by jeanrmiranda** [comment]
> I digged a bit more into your looking glass and found the reason it could still reach an invalid prefix. The routes are correctly rejected but it is still using the default gateway (which is fine and still safer from hijacks).
> Would you be able to change your default route to a transit dropping invalid prefixes? (GTT, Cogent, NTT, Telia)

Yes, please could you test again.
I changed the default gateway .

image

**Comment by lspgn** [comment]
Typo in the IP? 103.21.244.15 (invalid.rpki.cloudflare.com)
Thank you for the change, unfortuantely, I am still able to reach it (via Level 3 which does not filter invalids).

**Pull request merged**
