### PR TITLE
Add Pacswitch

### PR DESCRIPTION
**Pull request by FozzieHi**
Verification

### CODE REVIEW

**Comment by lspgn** [comment]
Missing ASN in the CSV.
Also they don't seem to have any route they announce signed https://rpki.cloudflare.com/?view=explorer&asn=55536
-> partially safe.
Mind double checking on https://sg-pub.ripe.net/jasper/rpki-web-test/

**Comment by FozzieHi** [comment]
I can add the ASN now.

**Comment by FozzieHi** [comment]
I assumed the test checked for signed routes.

**Comment by lspgn** [comment]
Cool, yes, go ahead:
Should be the following
`Pacswitch,ISP,filtering,partially safe,55536,27617`

**Pull request merged**
