### PR TITLE
Add AS19879 (prev. AS44658)

### PR DESCRIPTION
**Pull request by evnsh**
Propel / AS19879 (prev. AS44658) filters RPKI OV invalids since 2024-07-01

### CODE REVIEW

**Comment by evnsh** [comment]
Hello, this PR has been opened for a week, do you require more info?

**Comment by digizeph** [comment]
> Hello, this PR has been opened for a week, do you require more info? @digizeph

Hey @evnsh we currently do not have sufficient data on AS19879's RPKI invalid filtering. The upstream [AS52073](https://stats.labs.apnic.net/rpki/AS52073) does not seems to be doing RPKI filtering. Could you provide more info on your RPKI invalid filtering efforts? Thanks!

**Comment by evnsh** [comment]
Hey @digizeph, our upstream feed us a full view which like you said is not RPKI invalid filtered. We do the filtering on our side by rejecting RPKI invalid routes. We've started filtering RPKI invalid routes on the 1st of July which may explain why you do not have sufficient data.

**Comment by digizeph** [comment]
Close this ticket due to insufficient measurement data to support this pull request. Feel free to comment with additional data or evidences. Thank you for your efforts!

**Pull request closed without merging**
