### PR TITLE
Add Optimum

### PR DESCRIPTION
**Pull request by ddymko**
Adding Cablevision ISP

### CODE REVIEW

**Comment by jejenone** [comment]
Thanks for your PR! We are looking at the best way to add networks to the list. Stay tuned until we fix some bits of code.

**Comment by mxxcon** [comment]
"Cablevision" is probably not the correct name anymore.
In 2015 [Altice bought Cablevision](https://money.cnn.com/2015/09/16/media/cablevision-altice-deal/) (along with some other cable companies since then).
The company is now Altice and their product is named [Optimum](https://www.optimum.com).

**Comment by ddymko** [comment]
You are correct. I wasn't sure what to put down since the ASN checks brought back Cablevision

**Comment by ddymko** [comment]
Let me know if this should be changed to Optimum and I will clean that up while resolving the merge conflict

**Comment by jejenone** [comment]
Hi. Indeed let's use the latest naming and resolve conflicts. Can you submit fix ?

**Comment by ddymko** [comment]
Done - let me know if any other changes are needed

**Pull request merged**
