### PR TITLE
Update AS1221 status

### PR DESCRIPTION
**Pull request by markduffell**

### CODE REVIEW

**Comment by lspgn** [comment]
Hi Mark,
I'd prefer avoiding ASxxx in the name.
Otherwise, good to go (do you have a looking-glass to test?).
Thank you for deploying RPKI!

**Comment by lspgn** [comment]
One last thing, for the "latest updates" section: do you have a source/official statement to link to?

**Comment by markduffell** [comment]
Hi @lspgn unfortunately no domestic looking glass, best I can offer is a traceroute tool:
https://www.telstra.net/cgi-bin/trace

Should have a public post next week we can provide a link to.

**Comment by markduffell** [comment]
@lspgn source now added also for news update :)

**Comment by lspgn** [comment]
Awesome! Thank you @markduffell

**Pull request merged**
