### PR TITLE
patch

### PR DESCRIPTION
**Pull request by prakash-adhikari**
Broken link

### CODE REVIEW

**Comment by prakash-adhikari** [comment]
update README

**Comment by lspgn** [comment]
Hi @prakash-adhikari,
Thank you for the contribution,
Could you rebase on master?

We are looking at ways to add new networks to the list in an organized way. Stay tuned until we bring these changes next week.

In the meantime, I can apply the change on README but it needs to be out of the branch with the operator change.

**Comment by adamschwartz** [comment]
The portion of this that relates to the README link has been addressed with https://github.com/cloudflare/isbgpsafeyet.com/commit/d36e75add1ca51938e339331de09c46a5f8275e0. @lspgn I’ll let you handle the the portion which relates to the changes to `operators.csv`.

**Comment by prakash-adhikari** [comment]
Thanks!

**Pull request closed without merging**
