### PR TITLE
Populate table content from CSV file

### PR DESCRIPTION
**Pull request by vasturiano**
This PR moves the table content to a CSV file in `public/data/operators.csv`, for easiness of PR'ing future additions.

It reads the file content via xhr and does the DOM manipulation using `d3` (for convenience) but we could easily migrate that to vanilla if desirable.

### CODE REVIEW

**Comment by adamschwartz** [comment]
Since the table sits above the fold, this change causes a FOUC on page load. Including `d3.min.js` for simple DOM manipulation does feel unnecessary to me as it adds about `75k` to the payload and increases the waterfall by about `200ms`. In my testing the page went from loading in around `100ms` to loading in around `300ms`.

Additionally, since the data will be managed in this repo, the simplest thing to do would be to add a build step to generate the `index.html` file. We already deploy with Github Actions on pushes to master, so a merge of a PR on the data file would trigger a build and deploy in lockstep.

**Comment by dknecht** [comment]
Or do it on edge in worker.  Either works.  D3 makes sense to do data load when true visualization

**Comment by vasturiano** [comment]
I can migrate to vanilla js DOM manipulation to drop the d3 dependency. We'll still need `d3-dsv` to parse the CSV file, but that's a much smaller bundle.
https://bundlephobia.com/result?p=d3-dsv@1.2.0

**Comment by vasturiano** [comment]
Pushed a change to use vanilla js. Only remaining dependency is [d3-dsv](https://unpkg.com/d3-dsv@1.2.0/dist/d3-dsv.min.js). That's `3kB` loaded from [unpkg](https://unpkg.com/), which is cached on Cloudflare. If preferable we can move that to a vendor folder in the app.

**Comment by vasturiano** [comment]
Sounds good! I've added `d3-dsv` to `js/vendor`. For neatness also moved `sortables` there.

**Pull request merged**
