### PR TITLE
Add test to check for duplicate ASN in operators CSV and run with GitHub workflow

### PR DESCRIPTION
**Pull request by MitchellCash**
Since https://github.com/cloudflare/isbgpsafeyet.com/commit/9ef40ba82ba8158bccebf1cf8fb23349d6218c82 was merged, I notice it was accidentally added back again in https://github.com/cloudflare/isbgpsafeyet.com/commit/f6b9dec5b18c66f287a352de13b208700f0cc0d6 and then removed again in https://github.com/cloudflare/isbgpsafeyet.com/commit/7acf9a5668dcaf4c3c85dcfeff550c77369f9c3d.

Thought it might be nice to have some tests run on each PR/push to the repo to check for duplicate ASNs in `operators.csv`. Can extend with additional checks etc. pretty easy from here.

### CODE REVIEW

**Comment by FozzieHi** [comment]
The event "push" should cover all PRs anyway, I don't think there's a need for the event "pull_request" to be included, it'll just end up with the workflow running twice.

**Comment by MitchellCash** [comment]
@FozzieHi a `push` event occurs when changes are pushed to any branch in the repository, whereas, a `pull_request` event occurs on pull requests when they're opened/changed. These are two different types of events with different goals and won't make the workflow run twice.

See the single workflow run from this PR: https://github.com/cloudflare/isbgpsafeyet.com/actions/runs/85191962

Times when the workflow gets triggered:

`[pull_request]`
- When PR gets opened the workflow runs once against the most recent commit in the PR
- If PR has new commits pushed workflow runs once again to check latest changes

`[push]`
- If a maintainer pushes directly to any branch in the repo (no PR) the workflow runs once against the most recent commit that was just pushed
- Also when a maintainer merges a PR the workflow runs once against the merge commit in the repo

To me each of these events makes sense to run the workflow against so we can catch the mistakes as early as possible at any stage.

Better explanations than mine of all the different event types here https://help.github.com/en/actions/reference/events-that-trigger-workflows.

**Comment by FozzieHi** [comment]
Although when a PR is opened the push event would have already triggered and when a PR is merged it would also trigger the push event, I used to use push & pull_request for my CI and I just found push basically did everything I needed it to do.

**Comment by MitchellCash** [comment]
@FozzieHi when a PR is opened only the `pull_request` event is triggered and when the PR is merged the `push` event triggers.

This might on the surface seem like doing the same check twice, but not necessarily.

Sorry in advance, I just scribbled this out quickly now:

image

In the above when the pull request and the target branch diverge from their common base the merge commit isn't the exact same history as what was in the pull request as the target branch has had other work done to it in the mean time. So when the merge commit is pushed to the target branch we need to run our tests again against the new "git history" that may cause the tests to fail.

Example:
1. I branch `master` that does not have the Google Cloud provider
2. While I am working `master` has a commit pushed to it with Google Cloud as a provider
3. Later I open a PR to add Google Cloud provider based on the git history from where I branched
4. There are no merge conflicts and the maintainer merges the PR
5. Now there are two Google Cloud providers in the repo
6. We should run the automated test to check for this as it wasn't picked up by the maintainer doing the merge

Sorry it's a bit long winded, I hope I got it right as this is my understanding of it 😃

**Comment by lspgn** [comment]
Thank you this is great :)

**Pull request merged**
