### PR TITLE
Adding Vodafone IT and Fastweb

### PR DESCRIPTION
**Pull request by ecamellini**
## Vodafone IT

Added only to the operators' list, already present in the Twitter handles.

### ISP Details
https://asrank.caida.org/asns?asn=30722&type=search

### Test result
image

## Fastweb

Added to both the operators and Twitter handles.

### ISP Details
https://asrank.caida.org/asns?asn=12874&type=search

### Test result
image

## My Tweets about the two ISPs 😬

https://twitter.com/e_caml/status/1255577650174791681
https://twitter.com/e_caml/status/1255577650174791681

### CODE REVIEW

**Comment by lspgn** [comment]
Hi @ecamellini,
thank you for the PR,
could you insert into the list sorted by asrank? Otherwise good to go

**Comment by ecamellini** [comment]
@lspgn done 👍 Thanks for your review

**Comment by FozzieHi** [comment]
Can you resolve conflicts? after that looks ready to merge.

**Comment by ecamellini** [comment]
@FozzieHi done! Should be ready to merge.

**Comment by FozzieHi** [comment]
What about the twitter account for VodafoneIT?

**Comment by FozzieHi** [comment]
@lspgn LGTM

**Pull request merged**
