### PR TITLE
Handle WARP detection

### PR DESCRIPTION
**Pull request by lspgn**

### CODE REVIEW

**Comment by Tugzrida** [comment]
Hi, just wondering why the special case for warp is necessary? Whilst using warp, I can still load invalid.rpki.cloudflare.com and [RIPE's RPKI test](https://sg-pub.ripe.net/jasper/rpki-web-test/) fails.

To me, this would suggest that warp doesn't in fact implement RPKI validation. Could someone clarify this? Thanks.

**Comment by lspgn** [comment]
Hi @Tugzrida 
invalid.rpki.cloudflare.com is served directly from our PoPs. If you are connected using Warp (or similarly, using Cloudflare Workers to access the invalid page), the packets won't go over the Internet where we apply BGP origin validation.
It is a caveat of our setup.

If you are trying to reach an address outside Cloudflare and behind an invalid prefix, the route will be dropped by our routers. Overall, you should be less sensitive to route hijacks if you use Warp. If you are able to reach an invalid prefix not covered by a valid less-specific, please contact us.

**Comment by Tugzrida** [comment]
Ah right - Warp/Workers gets you inside Cloudflare already, so there's no BGP involved in reaching Cloudflare addresses.

As I mentioned, RIPE's test also shows a fail when run over warp. It looks to use the domains rpki-valid-beacon.meerval.net and rpki-invalid-beacon.meerval.net which seem to correctly be [valid](https://rpki.cloudflare.com/?view=validator&validateRoute=15562_209.24.1.0%2F24) and [invalid](https://rpki.cloudflare.com/?view=validator&validateRoute=15562_209.24.0.0%2F24) in the RPKI validator.

Thanks for your response!

**Comment by lspgn** [comment]
Which PoP are you connecting to? (https://cloudflare.com/cdn-cgi/trace should give you the info)
We use a default gateway due to certain constraints.
While we try to use transits which drop invalids, it not always possible everywhere. If the PoP you're using Warp from has a default pointed to Telia for instance, you shouldn't be able to reach the prefix (cf picture).
As more transits deploy RPKI, the safer we will be.
Additionally, while NTT is one of the RPKI-invalid filtering transit, the prefix behind rpki-invalid-beacon.meerval.net is an exception and still routed over their network.

Example:
Screenshot_20200422-212038

I hope this answers your question

**Comment by Tugzrida** [comment]
I'm on Sydney POP. Doing a trace over WARP shows the valid IP going Vocus->Open Transit->NTT, the invalid one going Telstra->Telstra Global->Sprint->NTT.

I had forgotten some of the finer details since I first looked at RPKI, so thanks for clarifying :) It makes sense that in the event a default route is used, that you're relying on the transit provider. It looks like there was a push for RPKI at APRICOT 2020 so hopefully more Aussie carriers will be onboard soon.

**Comment by lspgn** [comment]
Now you know the default gateway and which on the path do not do RPKI :p 

We do like feedback, thanks for asking those questions: there are some of the things we didn't summarize on the website but we're taking notes.
Hopefully this operation brings more eyes on the whole ecosystem. So, happy to help!
I'm looking forward to this! [AussieBB](https://twitter.com/Aussie_BB/status/1252067879358361600) announced they were deploying it soon.

**Comment by Tugzrida** [comment]
It may be worth adding an explanation somewhere as the current messaging is more that it's the ISPs fault for not implementing RPKI, whereas it could be their transit provider - particularly in the Australian market where there aren't as many options or _economical_ options. I guess it's a fine line of capturing the nuance vs allowing ISPs an easy-out on the whole thing by blaming it on someone else, and I guess a fair amount of ISPs peer directly with Cloudflare anyway so it's not relevant.

I'm on AussieBB myself and it's been very interesting to watch them build out their network and go up against some of the bigger players. Being able to talk to people from the network team and even the Managing Director on Whirlpool forums certainly gives a lot of interesting insight and details.

**Comment by lspgn** [comment]
I agree, we're currently reviewing the message, this was one of the main comment we received.

There are quite a few of those smaller ISPs around the world (Sonic in Bay Area for instance, Free in France years ago), they're pretty great and you can get technical people quickly.
Although, they don't always have the same resources as the "big ones": they may lack features (IPv6, RPKI) due to this and leverage may be limited against operators/hardware vendors :( .

**Pull request merged**
