### PR TITLE
add Liberty Global (AS6830) to data/operators.csv

### PR DESCRIPTION
**Pull request by nskalis**
add libertyglobal (as6830) to the operators list

### CODE REVIEW

**Comment by claudiodekker** [comment]
You just beat me to it, however, I don't understand how you got to the `signed + partially filtering` conclusion? Aren't they only `signed`?:

Screenshot 2020-04-20 at 13 35 36

**Comment by nskalis** [comment]
Hi,

- Our ROA’s are signed since years (all the ones we could – RIPE doesn’t support multi-LIR aggregates which will take a long time to deal with; carve outs with divest scenarios are a sheer nightmare – also do note AS origination doesn’t imply that AS has administrative ownership; sometimes it really is solely up to customers with own LIR to do it).
- We reject hijacks of our own PA address space, also since years.

**Comment by robert-scheck** [comment]
Speaking as AS6830 transit customer, I can not see that invalid ROAs would be dropped (I can reach e.g. 209.24.0.3, which is the testing IPv4 as per https://www.ripe.net/s/rpki-test).

**Comment by nskalis** [comment]
hi @robert-scheck the network prefix in question is `invalid` still though NTT doesn't seem to drop it, maybe it is whitelisted..

```
> show route 209.24.0.3 all terse 

inet.0: 969415 destinations, 3390023 routes (969299 active, 29 holddown, 514 hidden)
+ = Active Route, - = Last Active, * = Both

A V Destination        P Prf   Metric 1   Metric 2  Next hop        AS path
* I 209.24.0.0/24      B 170        250          0                  2914 15562 I
  invalid                                          >213.46.182.254
```

**Comment by robert-scheck** [comment]
Well, @nskalis, why aren't you dropping these invalid prefixes on your side? Or why would you whitelist them? Same for invalid.rpki.cloudflare.com, it's also reachable from AS6830.

**Comment by nskalis** [comment]
Our RPKI deployment runs in `passive` mode for now, we are in the stage of assessing the impact of flipping the switch.

**Comment by robert-scheck** [comment]
As you don't enforce RPKI, I would treat "signed" and "partially safe" as more suitable rather "signed + partially filtering", because own prefix filtering also works without RPKI (which this is mostly about).

**Comment by lspgn** [comment]
Hi @nskalis,
```
- We reject hijacks of our own PA address space, also since years.
```
Are you filtering only your prefixes?

In that case, `partially safe` is better but we shouldn't add `partially filtering`.

Regarding 209.24.0.0/24, yes, NTT uses it as a test prefix so they. have an exception to allow announcing it.

**Comment by nskalis** [comment]
thanks @lspgn, it has been amended (see new commit)

**Pull request merged**
