### PR TITLE
add Scaleway, 12876

### PR DESCRIPTION
**Pull request by adelbecq**

### CODE REVIEW

**Comment by lspgn** [comment]
hey @adelbecq, could you give more details? Definitely seeing packets going through Cogent from a server there (is it a default GW?).
The NTT prefix seems ok though 209.24.0.3

**Comment by jejenone** [comment]
On the other hand this traceroute seems to confirm:
`root@scw-frosty-tu:~# mtr --report 103.21.244.15
Start: Tue Apr 21 21:01:47 2020
HOST: scw-frosty-tu               Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 10.64.202.138              0.0%    10    0.3   0.5   0.3   0.8   0.0
  2.|-- 10.66.0.129                0.0%    10    1.0   1.3   0.8   2.5   0.3
  3.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
  4.|-- 10.1.94.212                0.0%    10    1.0   1.1   0.9   1.4   0.0
  5.|-- 208-225-47-212.int.cloud.  0.0%    10    1.3   1.2   1.0   1.4   0.0
  6.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0`

@adelbecq can you clarify status ? We'd love to add you at the top of the list in the cloud category!

**Comment by onemorepash** [comment]
@lspgn il est pas assez cher ton server pour avoir RPKI quoi :)

**Comment by adelbecq** [comment]
Hi,

we implement rpki validation & invalid drop on our standard network.
You could check it with a standard instances by example.

Tested ip is part of what we called "basic Bandwith" which is lower cost product and not our standard exit network, we don't get all of our IX/Peers and go with default route through Cogent or CTL/Level3, unfortunately, like you may know with default, we didn't get solution to rpki drop at this moment and should trust our Transits.

As our main network is safe, Should we reconsider as partialy safe in isbgpsafeyet.com PoV ?

Regards,
Adrien

**Comment by lspgn** [comment]
@onemorepash lol c'est un vieux qui devait normalement avoir la BW "Premium" avec Hopus et tout!

**Comment by lspgn** [comment]
@adelbecq sounds good to me. Thanks for the details.

**Pull request merged**
