### PR TITLE
Add Stellar Technologies

### PR DESCRIPTION
**Pull request by checktheroads**
Hello, I'd like to add Stellar Technologies (AS14525) to the list.

> Your ISP (Stellar Technologies Inc., AS14525) implements BGP safely. It correctly drops invalid prefixes. 

Thanks,
Matt

### CODE REVIEW

**Comment by lspgn** [comment]
Hello,
Thank you for your contribution, could you sort it by as rank?

**Comment by checktheroads** [comment]
Hi,

I've added another commit to sort by AS Rank.

That particular router displays the invalid route because we have the `bgp bestpath prefix-validate allow-invalid` flag in use for Cisco IOS-specific reasons. However, as you can see, the route is not used or advertised (`no best path` in the output above). From the device:

```
edge02.hnl01#show ip route 103.21.244.0
% Subnet not in table
```

```
edge02.hnl01#traceroute 103.21.244.0
Type escape sequence to abort.
Tracing the route to 103.21.244.0
VRF info: (vrf in name/id, vrf out name/id)
  1  *  *  *
  2  *  *  *
...
```

Thanks,
Matt

**Comment by lspgn** [comment]
LGTM
but I think something went wrong looking at the diff when sorting

**Comment by checktheroads** [comment]
I *believe* there were 2-3 other ASNs on the list not sorted, so my sorting sorted those as well. But if you see a problem, I can certainly try to correct it. That said, I was poking through the worker code, and I see that the data is sorted in JS anyway. :)

**Comment by lspgn** [comment]
Ah there was a line ending issues (windows is it with ^M :D ).
Fixed in #506, rebased and merged so you are still the contributor :) .
Will close this PR.
Thank you

**Pull request closed without merging**
