### PR TITLE
Update operators.csv

### PR DESCRIPTION
**Pull request by jboogman**
Swisscom has now fully deployed and is dropping invalids on customers, peers and upstreams :-)

### CODE REVIEW

**Comment by lspgn** [comment]
Thank you :) 
Do you have screenshot/traceroute?
I'm checking on the IP Plus Looking Glass but still seeing the route (route-server.ip-plus.net):
```
RS_AS3303>show ip bgp 103.21.244.15
BGP routing table entry for 103.21.244.0/24, version 0
BGP Bestpath: deterministic-med
Paths: (1 available, no best path)
  Not advertised to any peer
  Refresh Epoch 1
  (65000) 13335, (aggregated by 13335 172.69.108.1)
    138.187.128.73 (inaccessible) from 193.247.171.25 (138.187.128.83)
      Origin IGP, metric 550000, localpref 300, valid, confed-external
      Community: 3303:1004 3303:1007 3303:1030 3303:3066 13335:10192 13335:19020 13335:20500 13335:20530
```

**Comment by jboogman** [comment]
Hi Louis

here you are:

RP/0/RSP0/CPU0:i68cix-015#show ip bgp 103.21.244.15
Wed Jul 29 10:26:23.786 MEST
BGP routing table entry for 103.21.244.0/24
Versions:
  Process           bRIB/RIB  SendTblVer
  Speaker          138339933   138339933
Last Modified: Jul 29 10:25:34.619 for 00:00:49
Paths: (6 available, no best path)
  Not advertised to any peer
  Path #1: Received by speaker 0
  Not advertised to any peer
  3320 6453 13335, (aggregated by 13335 195.219.134.15), (received-only)
    80.156.163.165 from 80.156.163.165 (194.25.5.151)
      Origin IGP, metric 1000, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3320:1756 3320:2010 3320:9020 6453:2000 6453:2300 6453:2306
      Origin-AS validity: invalid
  Path #2: Received by speaker 0
  Not advertised to any peer
  3320 6453 13335, (aggregated by 13335 195.219.134.15)
    80.157.205.229 from 80.157.205.229 (194.25.5.151)
      Origin IGP, metric 701000, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3303:1021 3303:3066 3303:8199 3320:1756 3320:2010 3320:9020 6453:2000 6453:2300 6453:2306
      Origin-AS validity: invalid
  Path #3: Received by speaker 0
  Not advertised to any peer
  3320 6453 13335, (aggregated by 13335 195.219.134.15), (received-only)
    80.157.205.229 from 80.157.205.229 (194.25.5.151)
      Origin IGP, metric 1000, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3320:1756 3320:2010 3320:9020 6453:2000 6453:2300 6453:2306
      Origin-AS validity: invalid
  Path #4: Received by speaker 0
  Not advertised to any peer
  5511 13335, (aggregated by 13335 172.68.100.1), (received-only)
    81.52.188.133 from 81.52.188.133 (172.25.4.108)
      Origin IGP, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Origin-AS validity: invalid
  Path #5: Received by speaker 0
  Not advertised to any peer
  13335, (aggregated by 13335 172.69.108.1)
    192.65.185.228 from 192.65.185.228 (172.69.108.1)
      Origin IGP, metric 500000, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3303:1004 3303:1007 3303:1030 3303:3066 13335:10192 13335:19020 13335:20500 13335:20530
      Origin-AS validity: invalid
  Path #6: Received by speaker 0
  Not advertised to any peer
  13335, (aggregated by 13335 172.69.108.1), (received-only)
    192.65.185.228 from 192.65.185.228 (172.69.108.1)
      Origin IGP, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 13335:10192 13335:19020 13335:20500 13335:20530
      Origin-AS validity: invalid
RP/0/RSP0/CPU0:i68cix-015#


jan@ippeng-zhb-eng-02:~/sem/rpki$ lft -A 103.21.244.15
traceroute to 103.21.244.15 (103.21.244.15), 30 hops max, 60 byte packets
 1  194.209.45.2 (194.209.45.2) [AS3303]  0.591 ms  0.584 ms
 2  i79zhh-001-ten0-4-0-1x10210500.bb.ip-plus.net (217.193.48.1) [AS3303]  1.394 ms  1.343 ms
 3  * *
 4  * *
 5  * *
 6  * *
 7  * *
 8  * *
 9  * *
10  * *
11  * *
12  * *
13  * *
14  * *
15  * *
16  * *
17  * *
18  * *
19  * *
20  * *
21  * *
22  * *
23  * *
24  * *
25  * *
26  * *
27  * *
28  * *
29  * *
30  * *



Apparently there is an issue with XR6.3.3 that though 'bgp bestpath origin-as allow invalid' is configured on the customer neighbour-group only, it is applied globally 🙁

Fixed now

Best regards
Jan
________________________________
Von: Louis <notifications@github.com>
Gesendet: Mittwoch, 29. Juli 2020 10:20
An: cloudflare/isbgpsafeyet.com <isbgpsafeyet.com@noreply.github.com>
Cc: Boogman Jan, INI-ONE-WSN-EIS-SNS <Jan.Boogman@swisscom.com>; Author <author@noreply.github.com>
Betreff: Re: [cloudflare/isbgpsafeyet.com] Update operators.csv (#447)


Thank you :)
Do you have screenshot/traceroute?
I'm checking on the IP Plus Looking Glass but still seeing the route (route-server.ip-plus.net):

RS_AS3303>show ip bgp 103.21.244.15
BGP routing table entry for 103.21.244.0/24, version 0
BGP Bestpath: deterministic-med
Paths: (1 available, no best path)
  Not advertised to any peer
  Refresh Epoch 1
  (65000) 13335, (aggregated by 13335 172.69.108.1)
    138.187.128.73 (inaccessible) from 193.247.171.25 (138.187.128.83)
      Origin IGP, metric 550000, localpref 300, valid, confed-external
      Community: 3303:1004 3303:1007 3303:1030 3303:3066 13335:10192 13335:19020 13335:20500 13335:20530

**Comment by lspgn** [comment]
Thanks @jboogman 
Don't hesitate to publish an update if you have an official statement :) 
https://github.com/cloudflare/isbgpsafeyet.com/blob/351a5d03cc31a16708c51686139e12f25aeff183/src/index.html#L74

**Comment by jboogman** [comment]
Hi Louis

apparently your prefix isn't RPKI invalid anymore:

on our router in CERN:

RP/0/RSP0/CPU0:i68cix-015#sh bg 103.21.244.14Tue Oct 20 14:19:50.437 MEST
[…]
 13335, (aggregated by 13335 172.69.108.1)
    192.65.185.228 from 192.65.185.228 (172.69.108.1)
      Origin IGP, metric 500000, localpref 300, valid, external, group-best
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3303:1004 3303:1007 3303:1030 3303:3066 13335:10192 13335:19020 13335:20500 13335:20530
      Origin-AS validity: not-found

I see also that the niumber of ROAs from APNIC decreased a lot lately:

[cid:bb14cf6f-9b28-40af-b19a-36685a0be1de]

Best regards
Jan
________________________________
Von: Louis <notifications@github.com>
Gesendet: Mittwoch, 29. Juli 2020 10:37
An: cloudflare/isbgpsafeyet.com <isbgpsafeyet.com@noreply.github.com>
Cc: Boogman Jan, INI-ONE-WSN-EIS-SNS <Jan.Boogman@swisscom.com>; Mention <mention@noreply.github.com>
Betreff: Re: [cloudflare/isbgpsafeyet.com] Update operators.csv (#447)


Merged #447<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudflare%2Fisbgpsafeyet.com%2Fpull%2F447&data=02%7C01%7CJan.Boogman%40swisscom.com%7C4211ca928a484404fad608d8339ab04d%7C364e5b87c1c7420d9beec35d19b557a1%7C1%7C0%7C637316086754798076&sdata=BhlSuRBCYbybbb%2BdE2ZE0UUfaRHsQTlE8HqVLyHtNXg%3D&reserved=0> into master.

**Comment by jboogman** [comment]
Hi Louis

[I am not on Twitter and haven't found any other email for you, I hope this still reaches you]

it was our router at CIXP that caused the problem, the sessions to both validators seem to have stuck and a clear of them fixed it:


RP/0/RSP0/CPU0:i68cix-015#show bgp rpki server summary
Tue Oct 20 14:09:58.534 MEST

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
195.65.89.11            TCP:8282        ESTAB           6d15h           5087/419
195.65.89.9             TCP:8282        ESTAB           6d15h           4755/338



RP/0/RSP0/CPU0:i68cix-015#show bgp rpki server summary
Tue Oct 20 14:54:44.573 MEST

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
195.65.89.11            TCP:8282        ESTAB           00:00:01        163026/27721
195.65.89.9             TCP:8282        ESTAB           00:04:31        161283/27375


RP/0/RSP0/CPU0:i68cix-015#show bgp rpki table 103.21.244.0/23 max 23
Tue Oct 20 14:55:09.854 MEST

RPKI ROA entry for 103.21.244.0/23-23
  Origin-AS: 0 from 195.65.89.11
  Origin-AS: 0 from 195.65.89.9


  13335, (aggregated by 13335 172.69.108.1), (received-only)
    192.65.185.228 from 192.65.185.228 (172.69.108.1)
      Origin IGP, localpref 300, valid, external
      Received Path ID 0, Local Path ID 0, version 0
      Community: 13335:10192 13335:19020 13335:20500 13335:20530
      Origin-AS validity: invalid


Best regards
Jan
________________________________
Von: Boogman Jan, INI-ONE-WSN-EIS-SNS <Jan.Boogman@swisscom.com>
Gesendet: Dienstag, 20. Oktober 2020 14:30
An: cloudflare/isbgpsafeyet.com <isbgpsafeyet.com@noreply.github.com>; cloudflare/isbgpsafeyet.com <reply@reply.github.com>
Cc: Grädel Michel, GSE-CYD <Michel.Graedel@swisscom.com>
Betreff: AW: [cloudflare/isbgpsafeyet.com] Update operators.csv (#447)

Hi Louis

apparently your prefix isn't RPKI invalid anymore:

on our router in CERN:

RP/0/RSP0/CPU0:i68cix-015#sh bg 103.21.244.14Tue Oct 20 14:19:50.437 MEST
[…]
 13335, (aggregated by 13335 172.69.108.1)
    192.65.185.228 from 192.65.185.228 (172.69.108.1)
      Origin IGP, metric 500000, localpref 300, valid, external, group-best
      Received Path ID 0, Local Path ID 0, version 0
      Community: 3303:1004 3303:1007 3303:1030 3303:3066 13335:10192 13335:19020 13335:20500 13335:20530
      Origin-AS validity: not-found

I see also that the niumber of ROAs from APNIC decreased a lot lately:

[cid:e3f72736-19ca-4456-98a5-2c19ff0ff52b]

Best regards
Jan
________________________________
Von: Louis <notifications@github.com>
Gesendet: Mittwoch, 29. Juli 2020 10:37
An: cloudflare/isbgpsafeyet.com <isbgpsafeyet.com@noreply.github.com>
Cc: Boogman Jan, INI-ONE-WSN-EIS-SNS <Jan.Boogman@swisscom.com>; Mention <mention@noreply.github.com>
Betreff: Re: [cloudflare/isbgpsafeyet.com] Update operators.csv (#447)


Merged #447<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudflare%2Fisbgpsafeyet.com%2Fpull%2F447&data=02%7C01%7CJan.Boogman%40swisscom.com%7C4211ca928a484404fad608d8339ab04d%7C364e5b87c1c7420d9beec35d19b557a1%7C1%7C0%7C637316086754798076&sdata=BhlSuRBCYbybbb%2BdE2ZE0UUfaRHsQTlE8HqVLyHtNXg%3D&reserved=0> into master.

**Pull request merged**
