### PR TITLE
Add AS45595 Pakistan Telecom Company Limited (PTCL) in operators

### PR DESCRIPTION
**Pull request by armujahid**
ASN: https://ipinfo.io/AS45595
Tweet: https://twitter.com/armujahid/status/1251561174379966465
ASN rank is 1433: https://asrank.caida.org/asns?asn=45595&type=search

### CODE REVIEW

**Comment by armujahid** [comment]
Conflicts has been resolved. Now it is ready to merge. Let me know If I need to rebase.

**Comment by lspgn** [comment]
Sorry for the delay! Could you just sort the row with the as rank? otherwise, good to go

**Comment by armujahid** [comment]
Done

**Comment by lspgn** [comment]
Thank you!

**Pull request merged**
